name: Deploy para Hostinger

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependências do projeto
        run: npm install

      - name: Fazer o Build (Compilar o site)
        run: npm run build

      - name: Enviar arquivos via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/ # OBRIGATÓRIO: envia apenas a pasta compilada, não o código sujo
          server-dir: ./public_html/ # Pasta raiz da Hostinger
          timeout: 300000 # Aumenta o tempo de conexão para evitar o Timeout
